"""Schwab CLI quotes commands"""
from typing import List
from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from src.brokers.schwab.client import SchwabClient
from src.utils.schwab_token_manager import with_token_refresh

console = Console()

get_quotes_command = with_token_refresh(lambda symbols, fields: (console.print(f"[cyan]Fetching quotes for: {', '.join(symbols)}[/cyan]"), (lambda quotes: quotes and (console.print(_build_quotes_table(quotes)), "fundamental" in fields and _show_fundamentals(quotes)) or console.print("[red]No quotes retrieved[/red]"))(SchwabClient().get_quotes(symbols, fields)))[-1] if True else None)

_build_quotes_table = lambda quotes: (lambda table: [table.add_column(col, style=style, justify=justify, width=(12, None)[col != "Symbol"]) for col, style, justify in [("Symbol", "cyan", "left"), ("Last Price", "green", "right"), ("Change", "yellow", "right"), ("% Change", "yellow", "right"), ("Volume", "blue", "right"), ("Bid/Ask", "magenta", "center")]] and [table.add_row(symbol, q.lastPrice and f"${q.lastPrice:.2f}" or "N/A", f"[{('red', 'green')[q.netChange >= 0 if q.netChange else False]}]{q.netChange or 0:+.2f}[/{('red', 'green')[q.netChange >= 0 if q.netChange else False]}]", f"[{('red', 'green')[q.netChange >= 0 if q.netChange else False]}]{q.netPercentChange or 0:+.2f}%[/{('red', 'green')[q.netChange >= 0 if q.netChange else False]}]", q.totalVolume and f"{q.totalVolume:,}" or "N/A", (q.bidPrice and q.askPrice) and f"{q.bidPrice:.2f}/{q.askPrice:.2f}" or "N/A") for symbol, quote in quotes.items() for q in [quote.quote] if q] and table)(Table(title=f"Real-time Quotes ({len(quotes)} symbols)"))

_show_fundamentals = lambda quotes: console.print((lambda table: [table.add_column(col, style=style, justify=("left", "right")[col != "Symbol"]) for col, style in [("Symbol", "cyan"), ("P/E Ratio", "green"), ("EPS", "yellow"), ("Div Yield", "blue"), ("52W Volume", "magenta")]] and [table.add_row(symbol, f.peRatio and f"{f.peRatio:.2f}" or "N/A", f.eps and f"${f.eps:.2f}" or "N/A", f.divYield and f"{f.divYield:.2f}%" or "N/A", f.avg1YearVolume and f"{f.avg1YearVolume:,.0f}" or "N/A") for symbol, quote in quotes.items() for f in [quote.fundamental] if f] and table)(Table(title="Fundamental Data")))

get_futures_quotes_command = with_token_refresh(lambda symbols: (console.print(f"[cyan]Fetching futures quotes for: {', '.join(symbols)}[/cyan]"), (lambda quotes: quotes and console.print(_build_futures_table(quotes)) or console.print("[red]No futures quotes retrieved[/red]"))(SchwabClient().get_quotes(symbols, fields=["quote"])))[-1])

_build_futures_table = lambda quotes: (lambda table: [table.add_column(col, style=style, justify=justify, width=(12, None)[col != "Contract"]) for col, style, justify in [("Contract", "cyan", "left"), ("Last Price", "green", "right"), ("Change", "yellow", "right"), ("Bid/Ask", "blue", "center"), ("Volume", "magenta", "right"), ("High/Low", "white", "center")]] and [table.add_row(symbol, q.lastPrice and f"${q.lastPrice:.2f}" or "N/A", f"[{('red', 'green')[q.netChange >= 0 if q.netChange else False]}]{q.netChange or 0:+.2f} ({q.netPercentChange or 0:+.2f}%)[/{('red', 'green')[q.netChange >= 0 if q.netChange else False]}]", (q.bidPrice and q.askPrice) and f"{q.bidPrice:.2f}/{q.askPrice:.2f}" or "N/A", q.totalVolume and f"{q.totalVolume:,}" or "N/A", (q.highPrice and q.lowPrice) and f"H:{q.highPrice:.2f} L:{q.lowPrice:.2f}" or "N/A") for symbol, quote in quotes.items() for q in [quote.quote] if q] and table)(Table(title=f"Futures Quotes ({len(quotes)} contracts)"))

get_options_chain_command = with_token_refresh(lambda symbol, strike_count=5, days_to_expiration=30: (console.print(f"[cyan]Fetching options chain for {symbol}[/cyan]"), (lambda chain: (console.print(Panel.fit(f"[green]Options Chain for {symbol}[/green]\nUnderlying Price: ${chain.underlyingPrice:,.2f}\nTotal Contracts: {chain.numberOfContracts}\nIV: {chain.volatility:.2f}%", title="Options Summary", border_style="green")), _show_options_table("CALLS", chain.callExpDateMap, "green"), _show_options_table("PUTS", chain.putExpDateMap, "red")))(SchwabClient().get_options_chain(symbol=symbol, contract_type="ALL", strike_count=strike_count, days_to_expiration=days_to_expiration)))[-1])

_show_options_table = lambda option_type, exp_date_map, color: console.print((lambda table: [table.add_column(col, style=style, justify=justify) for col, style, justify in [("Strike", "cyan", "right"), ("Exp Date", "yellow", "left"), ("Bid/Ask", color, "center"), ("Volume", "blue", "right"), ("Open Int", "magenta", "right"), ("IV", "white", "right")]] and [table.add_row(f"${c.strikePrice:.2f}", c.expirationDate, f"{c.bid:.2f}/{c.ask:.2f}", str(c.totalVolume), str(c.openInterest), c.volatility and f"{c.volatility:.1f}%" or "N/A") for c in [contracts[0] for strikes in exp_date_map.values() for contracts in strikes.values() if contracts]] and table)(Table(title=option_type)))